services:
  game:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: game
    ports:
      - '3000:3000'
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-postgres}'
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - game-network

  db:
    image: postgres:16-alpine
    container_name: todoapp-db
    environment:
      POSTGRES_DB: '${POSTGRES_DB:-postgres}'
      POSTGRES_USER: '${POSTGRES_USER:-postgres}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-postgres}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-todoapp} -d ${POSTGRES_DB:-todoapp}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - game-network


volumes:
  postgres_data:
    name: game-postgres-data
    driver: local

networks:
  game-network:
    name: game-network
    driver: bridge